### ISSUE TITLE
Access Google CalenderAPI

### ISSUE THREAD

**Issue by ShivanS93** [ShivanS93/bookmyhaircut#2]
# TODO:

- [ ] Access Google Calender API
- [ ] access any appointments
- [ ] Look for a previous haircut appointment
- [ ] Look x number of weeks ahead to block and book next weeks apt.

## Resources:
* https://developers.google.com/calendar/v3/reference
